/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as QuestionsRouteImport } from './routes/questions'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as WinnersRouteImport } from './routes/winners'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedSubmitSpaceRouteImport } from './routes/_authenticated/submit-space'
import { Route as DispatchesIndexRouteImport } from './routes/dispatches.index'
import { Route as DispatchesSlugRouteImport } from './routes/dispatches.$slug'
import { Route as GuidesIndexRouteImport } from './routes/guides.index'
import { Route as GuidesSlugRouteImport } from './routes/guides.$slug'
import { Route as SpacesIndexRouteImport } from './routes/spaces.index'
import { Route as SpacesSlugRouteImport } from './routes/spaces.$slug'
import { Route as AuthenticatedAdminSpacesRouteImport } from './routes/_authenticated/admin.spaces'
import { Route as AuthenticatedQuestionsAskRouteImport } from './routes/_authenticated/questions.ask'
import { Route as AuthenticatedReviewSlugRouteImport } from './routes/_authenticated/review.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionsRoute = QuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const WinnersRoute = WinnersRouteImport.update({
  id: '/winners',
  path: '/winners',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSubmitSpaceRoute =
  AuthenticatedSubmitSpaceRouteImport.update({
    id: '/submit-space',
    path: '/submit-space',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const DispatchesIndexRoute = DispatchesIndexRouteImport.update({
  id: '/dispatches/',
  path: '/dispatches/',
  getParentRoute: () => rootRouteImport,
} as any)
const DispatchesSlugRoute = DispatchesSlugRouteImport.update({
  id: '/dispatches/$slug',
  path: '/dispatches/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/guides/$slug',
  path: '/guides/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SpacesIndexRoute = SpacesIndexRouteImport.update({
  id: '/spaces/',
  path: '/spaces/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpacesSlugRoute = SpacesSlugRouteImport.update({
  id: '/spaces/$slug',
  path: '/spaces/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminSpacesRoute =
  AuthenticatedAdminSpacesRouteImport.update({
    id: '/admin/spaces',
    path: '/admin/spaces',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedQuestionsAskRoute =
  AuthenticatedQuestionsAskRouteImport.update({
    id: '/questions/ask',
    path: '/questions/ask',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReviewSlugRoute = AuthenticatedReviewSlugRouteImport.update({
  id: '/review/$slug',
  path: '/review/$slug',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/questions': typeof QuestionsRoute
  '/terms': typeof TermsRoute
  '/winners': typeof WinnersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/submit-space': typeof AuthenticatedSubmitSpaceRoute
  '/dispatches/$slug': typeof DispatchesSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/spaces/$slug': typeof SpacesSlugRoute
  '/dispatches/': typeof DispatchesIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/spaces/': typeof SpacesIndexRoute
  '/admin/spaces': typeof AuthenticatedAdminSpacesRoute
  '/questions/ask': typeof AuthenticatedQuestionsAskRoute
  '/review/$slug': typeof AuthenticatedReviewSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/questions': typeof QuestionsRoute
  '/terms': typeof TermsRoute
  '/winners': typeof WinnersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/submit-space': typeof AuthenticatedSubmitSpaceRoute
  '/dispatches/$slug': typeof DispatchesSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/spaces/$slug': typeof SpacesSlugRoute
  '/dispatches': typeof DispatchesIndexRoute
  '/guides': typeof GuidesIndexRoute
  '/spaces': typeof SpacesIndexRoute
  '/admin/spaces': typeof AuthenticatedAdminSpacesRoute
  '/questions/ask': typeof AuthenticatedQuestionsAskRoute
  '/review/$slug': typeof AuthenticatedReviewSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/questions': typeof QuestionsRoute
  '/terms': typeof TermsRoute
  '/winners': typeof WinnersRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/submit-space': typeof AuthenticatedSubmitSpaceRoute
  '/dispatches/$slug': typeof DispatchesSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/spaces/$slug': typeof SpacesSlugRoute
  '/dispatches/': typeof DispatchesIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/spaces/': typeof SpacesIndexRoute
  '/_authenticated/admin/spaces': typeof AuthenticatedAdminSpacesRoute
  '/_authenticated/questions/ask': typeof AuthenticatedQuestionsAskRoute
  '/_authenticated/review/$slug': typeof AuthenticatedReviewSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/careers'
    | '/contact'
    | '/privacy'
    | '/questions'
    | '/terms'
    | '/winners'
    | '/dashboard'
    | '/submit-space'
    | '/dispatches/$slug'
    | '/guides/$slug'
    | '/spaces/$slug'
    | '/dispatches/'
    | '/guides/'
    | '/spaces/'
    | '/admin/spaces'
    | '/questions/ask'
    | '/review/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/careers'
    | '/contact'
    | '/privacy'
    | '/questions'
    | '/terms'
    | '/winners'
    | '/dashboard'
    | '/submit-space'
    | '/dispatches/$slug'
    | '/guides/$slug'
    | '/spaces/$slug'
    | '/dispatches'
    | '/guides'
    | '/spaces'
    | '/admin/spaces'
    | '/questions/ask'
    | '/review/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/careers'
    | '/contact'
    | '/privacy'
    | '/questions'
    | '/terms'
    | '/winners'
    | '/_authenticated/dashboard'
    | '/_authenticated/submit-space'
    | '/dispatches/$slug'
    | '/guides/$slug'
    | '/spaces/$slug'
    | '/dispatches/'
    | '/guides/'
    | '/spaces/'
    | '/_authenticated/admin/spaces'
    | '/_authenticated/questions/ask'
    | '/_authenticated/review/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  PrivacyRoute: typeof PrivacyRoute
  QuestionsRoute: typeof QuestionsRoute
  TermsRoute: typeof TermsRoute
  WinnersRoute: typeof WinnersRoute
  DispatchesSlugRoute: typeof DispatchesSlugRoute
  GuidesSlugRoute: typeof GuidesSlugRoute
  SpacesSlugRoute: typeof SpacesSlugRoute
  DispatchesIndexRoute: typeof DispatchesIndexRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
  SpacesIndexRoute: typeof SpacesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questions': {
      id: '/questions'
      path: '/questions'
      fullPath: '/questions'
      preLoaderRoute: typeof QuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/winners': {
      id: '/winners'
      path: '/winners'
      fullPath: '/winners'
      preLoaderRoute: typeof WinnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/submit-space': {
      id: '/_authenticated/submit-space'
      path: '/submit-space'
      fullPath: '/submit-space'
      preLoaderRoute: typeof AuthenticatedSubmitSpaceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/dispatches/': {
      id: '/dispatches/'
      path: '/dispatches'
      fullPath: '/dispatches/'
      preLoaderRoute: typeof DispatchesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatches/$slug': {
      id: '/dispatches/$slug'
      path: '/dispatches/$slug'
      fullPath: '/dispatches/$slug'
      preLoaderRoute: typeof DispatchesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/guides/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spaces/': {
      id: '/spaces/'
      path: '/spaces'
      fullPath: '/spaces/'
      preLoaderRoute: typeof SpacesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spaces/$slug': {
      id: '/spaces/$slug'
      path: '/spaces/$slug'
      fullPath: '/spaces/$slug'
      preLoaderRoute: typeof SpacesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/spaces': {
      id: '/_authenticated/admin/spaces'
      path: '/admin/spaces'
      fullPath: '/admin/spaces'
      preLoaderRoute: typeof AuthenticatedAdminSpacesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/questions/ask': {
      id: '/_authenticated/questions/ask'
      path: '/questions/ask'
      fullPath: '/questions/ask'
      preLoaderRoute: typeof AuthenticatedQuestionsAskRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/review/$slug': {
      id: '/_authenticated/review/$slug'
      path: '/review/$slug'
      fullPath: '/review/$slug'
      preLoaderRoute: typeof AuthenticatedReviewSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSubmitSpaceRoute: typeof AuthenticatedSubmitSpaceRoute
  AuthenticatedAdminSpacesRoute: typeof AuthenticatedAdminSpacesRoute
  AuthenticatedQuestionsAskRoute: typeof AuthenticatedQuestionsAskRoute
  AuthenticatedReviewSlugRoute: typeof AuthenticatedReviewSlugRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSubmitSpaceRoute: AuthenticatedSubmitSpaceRoute,
  AuthenticatedAdminSpacesRoute: AuthenticatedAdminSpacesRoute,
  AuthenticatedQuestionsAskRoute: AuthenticatedQuestionsAskRoute,
  AuthenticatedReviewSlugRoute: AuthenticatedReviewSlugRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  PrivacyRoute: PrivacyRoute,
  QuestionsRoute: QuestionsRoute,
  TermsRoute: TermsRoute,
  WinnersRoute: WinnersRoute,
  DispatchesSlugRoute: DispatchesSlugRoute,
  GuidesSlugRoute: GuidesSlugRoute,
  SpacesSlugRoute: SpacesSlugRoute,
  DispatchesIndexRoute: DispatchesIndexRoute,
  GuidesIndexRoute: GuidesIndexRoute,
  SpacesIndexRoute: SpacesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
